// バージョン3を利用する

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: proto/category.proto

// パッケージの宣言

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CategoryService_List_FullMethodName = "/proto.CategoryService/List"
	CategoryService_ById_FullMethodName = "/proto.CategoryService/ById"
)

// CategoryServiceClient is the client API for CategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryServiceClient interface {
	// すべてのカテゴリを取得して返す
	List(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoriesResult, error)
	// 指定されたIDのカテゴリを取得して返す
	ById(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoryResult, error)
}

type categoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryServiceClient(cc grpc.ClientConnInterface) CategoryServiceClient {
	return &categoryServiceClient{cc}
}

func (c *categoryServiceClient) List(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoriesResult, error) {
	out := new(CategoriesResult)
	err := c.cc.Invoke(ctx, CategoryService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) ById(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoryResult, error) {
	out := new(CategoryResult)
	err := c.cc.Invoke(ctx, CategoryService_ById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceServer is the server API for CategoryService service.
// All implementations must embed UnimplementedCategoryServiceServer
// for forward compatibility
type CategoryServiceServer interface {
	// すべてのカテゴリを取得して返す
	List(context.Context, *CategoryParam) (*CategoriesResult, error)
	// 指定されたIDのカテゴリを取得して返す
	ById(context.Context, *CategoryParam) (*CategoryResult, error)
	mustEmbedUnimplementedCategoryServiceServer()
}

// UnimplementedCategoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCategoryServiceServer struct {
}

func (UnimplementedCategoryServiceServer) List(context.Context, *CategoryParam) (*CategoriesResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCategoryServiceServer) ById(context.Context, *CategoryParam) (*CategoryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ById not implemented")
}
func (UnimplementedCategoryServiceServer) mustEmbedUnimplementedCategoryServiceServer() {}

// UnsafeCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryServiceServer will
// result in compilation errors.
type UnsafeCategoryServiceServer interface {
	mustEmbedUnimplementedCategoryServiceServer()
}

func RegisterCategoryServiceServer(s grpc.ServiceRegistrar, srv CategoryServiceServer) {
	s.RegisterService(&CategoryService_ServiceDesc, srv)
}

func _CategoryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).List(ctx, req.(*CategoryParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_ById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).ById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryService_ById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).ById(ctx, req.(*CategoryParam))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryService_ServiceDesc is the grpc.ServiceDesc for CategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CategoryService",
	HandlerType: (*CategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CategoryService_List_Handler,
		},
		{
			MethodName: "ById",
			Handler:    _CategoryService_ById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/category.proto",
}

const (
	CategoryUpService_Create_FullMethodName = "/proto.CategoryUpService/Create"
	CategoryUpService_Update_FullMethodName = "/proto.CategoryUpService/Update"
	CategoryUpService_Delete_FullMethodName = "/proto.CategoryUpService/Delete"
)

// CategoryUpServiceClient is the client API for CategoryUpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryUpServiceClient interface {
	// 商品カテゴリを追加した結果を返す
	Create(ctx context.Context, in *CategoryUpParam, opts ...grpc.CallOption) (*CategoryUpResult, error)
	// 商品カテゴリを更新した結果を返す
	Update(ctx context.Context, in *CategoryUpParam, opts ...grpc.CallOption) (*CategoryUpResult, error)
	// 商品カテゴリを削除した結果を返す
	Delete(ctx context.Context, in *CategoryUpParam, opts ...grpc.CallOption) (*CategoryUpResult, error)
}

type categoryUpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryUpServiceClient(cc grpc.ClientConnInterface) CategoryUpServiceClient {
	return &categoryUpServiceClient{cc}
}

func (c *categoryUpServiceClient) Create(ctx context.Context, in *CategoryUpParam, opts ...grpc.CallOption) (*CategoryUpResult, error) {
	out := new(CategoryUpResult)
	err := c.cc.Invoke(ctx, CategoryUpService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryUpServiceClient) Update(ctx context.Context, in *CategoryUpParam, opts ...grpc.CallOption) (*CategoryUpResult, error) {
	out := new(CategoryUpResult)
	err := c.cc.Invoke(ctx, CategoryUpService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryUpServiceClient) Delete(ctx context.Context, in *CategoryUpParam, opts ...grpc.CallOption) (*CategoryUpResult, error) {
	out := new(CategoryUpResult)
	err := c.cc.Invoke(ctx, CategoryUpService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryUpServiceServer is the server API for CategoryUpService service.
// All implementations must embed UnimplementedCategoryUpServiceServer
// for forward compatibility
type CategoryUpServiceServer interface {
	// 商品カテゴリを追加した結果を返す
	Create(context.Context, *CategoryUpParam) (*CategoryUpResult, error)
	// 商品カテゴリを更新した結果を返す
	Update(context.Context, *CategoryUpParam) (*CategoryUpResult, error)
	// 商品カテゴリを削除した結果を返す
	Delete(context.Context, *CategoryUpParam) (*CategoryUpResult, error)
	mustEmbedUnimplementedCategoryUpServiceServer()
}

// UnimplementedCategoryUpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCategoryUpServiceServer struct {
}

func (UnimplementedCategoryUpServiceServer) Create(context.Context, *CategoryUpParam) (*CategoryUpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCategoryUpServiceServer) Update(context.Context, *CategoryUpParam) (*CategoryUpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCategoryUpServiceServer) Delete(context.Context, *CategoryUpParam) (*CategoryUpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCategoryUpServiceServer) mustEmbedUnimplementedCategoryUpServiceServer() {}

// UnsafeCategoryUpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryUpServiceServer will
// result in compilation errors.
type UnsafeCategoryUpServiceServer interface {
	mustEmbedUnimplementedCategoryUpServiceServer()
}

func RegisterCategoryUpServiceServer(s grpc.ServiceRegistrar, srv CategoryUpServiceServer) {
	s.RegisterService(&CategoryUpService_ServiceDesc, srv)
}

func _CategoryUpService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryUpServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryUpService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryUpServiceServer).Create(ctx, req.(*CategoryUpParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryUpService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryUpServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryUpService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryUpServiceServer).Update(ctx, req.(*CategoryUpParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryUpService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryUpServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryUpService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryUpServiceServer).Delete(ctx, req.(*CategoryUpParam))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryUpService_ServiceDesc is the grpc.ServiceDesc for CategoryUpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryUpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CategoryUpService",
	HandlerType: (*CategoryUpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CategoryUpService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CategoryUpService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CategoryUpService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/category.proto",
}
