// バージョン3を利用する

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: proto/product.proto

// パッケージの宣言

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductService_List_FullMethodName      = "/proto.ProductService/List"
	ProductService_ById_FullMethodName      = "/proto.ProductService/ById"
	ProductService_ByKeyword_FullMethodName = "/proto.ProductService/ByKeyword"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	// すべての商品を取得して返す
	List(ctx context.Context, in *ProductParam, opts ...grpc.CallOption) (*ProductsResult, error)
	// 指定されたIDの商品を取得して返す
	ById(ctx context.Context, in *ProductParam, opts ...grpc.CallOption) (*ProductResult, error)
	// 指定されたキーワードの商品を取得して返す
	ByKeyword(ctx context.Context, in *ProductParam, opts ...grpc.CallOption) (*ProductsResult, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) List(ctx context.Context, in *ProductParam, opts ...grpc.CallOption) (*ProductsResult, error) {
	out := new(ProductsResult)
	err := c.cc.Invoke(ctx, ProductService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ById(ctx context.Context, in *ProductParam, opts ...grpc.CallOption) (*ProductResult, error) {
	out := new(ProductResult)
	err := c.cc.Invoke(ctx, ProductService_ById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ByKeyword(ctx context.Context, in *ProductParam, opts ...grpc.CallOption) (*ProductsResult, error) {
	out := new(ProductsResult)
	err := c.cc.Invoke(ctx, ProductService_ByKeyword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	// すべての商品を取得して返す
	List(context.Context, *ProductParam) (*ProductsResult, error)
	// 指定されたIDの商品を取得して返す
	ById(context.Context, *ProductParam) (*ProductResult, error)
	// 指定されたキーワードの商品を取得して返す
	ByKeyword(context.Context, *ProductParam) (*ProductsResult, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) List(context.Context, *ProductParam) (*ProductsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProductServiceServer) ById(context.Context, *ProductParam) (*ProductResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ById not implemented")
}
func (UnimplementedProductServiceServer) ByKeyword(context.Context, *ProductParam) (*ProductsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ByKeyword not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).List(ctx, req.(*ProductParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ById(ctx, req.(*ProductParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ByKeyword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ByKeyword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ByKeyword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ByKeyword(ctx, req.(*ProductParam))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ProductService_List_Handler,
		},
		{
			MethodName: "ById",
			Handler:    _ProductService_ById_Handler,
		},
		{
			MethodName: "ByKeyword",
			Handler:    _ProductService_ByKeyword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product.proto",
}

const (
	ProductUpService_Create_FullMethodName = "/proto.ProductUpService/Create"
	ProductUpService_Update_FullMethodName = "/proto.ProductUpService/Update"
	ProductUpService_Delete_FullMethodName = "/proto.ProductUpService/Delete"
)

// ProductUpServiceClient is the client API for ProductUpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductUpServiceClient interface {
	// 商品カテゴリを追加した結果を返す
	Create(ctx context.Context, in *ProductUpParam, opts ...grpc.CallOption) (*ProductUpResult, error)
	// 商品カテゴリを更新した結果を返す
	Update(ctx context.Context, in *ProductUpParam, opts ...grpc.CallOption) (*ProductUpResult, error)
	// 商品カテゴリを削除した結果を返す
	Delete(ctx context.Context, in *ProductUpParam, opts ...grpc.CallOption) (*ProductUpResult, error)
}

type productUpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductUpServiceClient(cc grpc.ClientConnInterface) ProductUpServiceClient {
	return &productUpServiceClient{cc}
}

func (c *productUpServiceClient) Create(ctx context.Context, in *ProductUpParam, opts ...grpc.CallOption) (*ProductUpResult, error) {
	out := new(ProductUpResult)
	err := c.cc.Invoke(ctx, ProductUpService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productUpServiceClient) Update(ctx context.Context, in *ProductUpParam, opts ...grpc.CallOption) (*ProductUpResult, error) {
	out := new(ProductUpResult)
	err := c.cc.Invoke(ctx, ProductUpService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productUpServiceClient) Delete(ctx context.Context, in *ProductUpParam, opts ...grpc.CallOption) (*ProductUpResult, error) {
	out := new(ProductUpResult)
	err := c.cc.Invoke(ctx, ProductUpService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductUpServiceServer is the server API for ProductUpService service.
// All implementations must embed UnimplementedProductUpServiceServer
// for forward compatibility
type ProductUpServiceServer interface {
	// 商品カテゴリを追加した結果を返す
	Create(context.Context, *ProductUpParam) (*ProductUpResult, error)
	// 商品カテゴリを更新した結果を返す
	Update(context.Context, *ProductUpParam) (*ProductUpResult, error)
	// 商品カテゴリを削除した結果を返す
	Delete(context.Context, *ProductUpParam) (*ProductUpResult, error)
	mustEmbedUnimplementedProductUpServiceServer()
}

// UnimplementedProductUpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductUpServiceServer struct {
}

func (UnimplementedProductUpServiceServer) Create(context.Context, *ProductUpParam) (*ProductUpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProductUpServiceServer) Update(context.Context, *ProductUpParam) (*ProductUpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProductUpServiceServer) Delete(context.Context, *ProductUpParam) (*ProductUpResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProductUpServiceServer) mustEmbedUnimplementedProductUpServiceServer() {}

// UnsafeProductUpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductUpServiceServer will
// result in compilation errors.
type UnsafeProductUpServiceServer interface {
	mustEmbedUnimplementedProductUpServiceServer()
}

func RegisterProductUpServiceServer(s grpc.ServiceRegistrar, srv ProductUpServiceServer) {
	s.RegisterService(&ProductUpService_ServiceDesc, srv)
}

func _ProductUpService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductUpServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductUpService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductUpServiceServer).Create(ctx, req.(*ProductUpParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductUpService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductUpServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductUpService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductUpServiceServer).Update(ctx, req.(*ProductUpParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductUpService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductUpServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductUpService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductUpServiceServer).Delete(ctx, req.(*ProductUpParam))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductUpService_ServiceDesc is the grpc.ServiceDesc for ProductUpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductUpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductUpService",
	HandlerType: (*ProductUpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductUpService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductUpService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProductUpService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product.proto",
}
